foo: bar
logging:
  level: INFO
  loggers:
    "com.multitenancy.example.resource.ProjectResource": INFO
database:
  # Mysql JDBC driver
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost/example_development
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
